In [1]:
#Importing with custom names to avoid issues with numpy / sympy matrix
from cvxopt import matrix as cvxopt_matrix
from cvxopt import solvers as cvxopt_solvers
import numpy as np

In [23]:
#Initializing values and computing H. Note the 1. to force to float type
x_neg = np.array([[4,2],[2,4],[4,4]])
y_neg = np.array([-1,-1,-1])
x_pos = np.array([[2,2]])
y_pos = np.array([1])

#Data for the next section
X = np.vstack((x_pos, x_neg))
y = np.concatenate((y_pos,y_neg))
m,n = X.shape #Size of matrix
y = y.reshape(-1,1)*1.0 # multiply by 1.0 for made it to float number

X_dash = y * X
QQ = np.dot(X_dash , X_dash.T)*1.0

In [24]:
#Converting into cvxopt format
Q = cvxopt_matrix(QQ)
e = cvxopt_matrix(-np.ones((m, 1)))
I = cvxopt_matrix(-np.eye(m))
vectorZero = cvxopt_matrix(np.zeros(m)) 
y_tran = cvxopt_matrix(y.reshape(1, -1))
Zero = cvxopt_matrix(np.zeros(1))

In [29]:
print('Q=\n{}e=\n{}I=\n{}vectorZero=\n{}y_tran=\n{}Zero=\n{}'.format(Q,e,I,vectorZero,y_tran,Zero))

Q=
[ 8.00e+00 -1.20e+01 -1.20e+01 -1.60e+01]
[-1.20e+01  2.00e+01  1.60e+01  2.40e+01]
[-1.20e+01  1.60e+01  2.00e+01  2.40e+01]
[-1.60e+01  2.40e+01  2.40e+01  3.20e+01]
e=
[-1.00e+00]
[-1.00e+00]
[-1.00e+00]
[-1.00e+00]
I=
[-1.00e+00 -0.00e+00 -0.00e+00 -0.00e+00]
[-0.00e+00 -1.00e+00 -0.00e+00 -0.00e+00]
[-0.00e+00 -0.00e+00 -1.00e+00 -0.00e+00]
[-0.00e+00 -0.00e+00 -0.00e+00 -1.00e+00]
vectorZero=
[ 0.00e+00]
[ 0.00e+00]
[ 0.00e+00]
[ 0.00e+00]
y_tran=
[ 1.00e+00 -1.00e+00 -1.00e+00 -1.00e+00]
Zero=
[ 0.00e+00]



In [30]:
#Setting solver parameters (change default to decrease tolerance) 
cvxopt_solvers.options['show_progress'] = False
cvxopt_solvers.options['abstol'] = 1e-10
cvxopt_solvers.options['reltol'] = 1e-10
cvxopt_solvers.options['feastol'] = 1e-10

In [49]:
#Run solver
sol = cvxopt_solvers.qp(Q,e,I,vectorZero,y_tran,Zero)
alphas = np.array(sol['x'])
print('Alphas=\n',alphas)

Alphas=
 [[1.00000000e+00]
 [5.00000000e-01]
 [5.00000000e-01]
 [1.92369414e-12]]


In [89]:
#w parameter in vectorized form
w = (np.dot((y * alphas).T, X)).reshape(-1,1)
#Selecting the set of indices S corresponding to non zero parameters
S = (alphas > 1e-10).flatten()
#Computing b
b = y[S] - np.dot(X[S], w)

In [100]:
#Display results
print('Alphas = ',alphas[alphas > 0])
print('w = {},{}'.format(w[0][0],w[1][0]))
print('b = ', b[0][0])

Alphas =  [1.00000000e+00 5.00000000e-01 5.00000000e-01 1.92369414e-12]
w = -1.000000000002493,-1.0000000000024933
b =  5.0000000000099725
